{
 "title": "Front End Observabiliy Custom Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "AppName",
    "label": "App",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Cart Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Cart Adds",
   "type": "stat",
   "description": "Number of times \"Add to Cart\" Custom event has been fired from FE for given time frame. \n\nThis same logic can be used to count any custom event. (May want to compare checkouts started vs checkouts completed). ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$AppName\"} | logfmt | event_name = `CartAdd` [$__range]))"
    }
   ]
  },
  {
   "title": "Cart Totals",
   "type": "stat",
   "description": "Sums the custom values sent from the UI when \"Add to Cart\" is clicked. \n\n",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(app) (sum_over_time({app=\"$AppName\"} | logfmt | event_name = `CartAdd` | unwrap event_data_cartValue [1m]))",
     "legendFormat": "Sum of Products added to cart"
    }
   ]
  },
  {
   "title": "Average Product Price",
   "type": "stat",
   "description": "Sums the custom values sent from the UI when \"Add to Cart\" is clicked. \n\n",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  { "title": "User Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Number of Sign ins",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"$AppName\"} | logfmt | event_name = `SignIn` [$__range]))"
    }
   ]
  },
  {
   "title": "Number of Events per User Type",
   "type": "bargauge",
   "description": "Number of times session_start has been invoked by user type",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(user_attr_customerType) (count_over_time({app=\"$AppName\"} | logfmt [$__range]))"
    }
   ]
  },
  {
   "title": "Average Cart by User Type",
   "type": "stat",
   "description": "Sums the custom values sent from the UI when \"Add to Cart\" is clicked. \n\n",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(user_attr_customerType) (avg_over_time({app=\"test-app2\"} | logfmt | event_name = `CartAdd` | unwrap event_data_cartValue [$__interval]))",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "All Logs",
   "type": "logs",
   "description": "All measurements and events sent by the Faro SDK. ",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{app=\"$AppName\"} | logfmt"
    }
   ]
  },
  {
   "title": "Add to Cart Log",
   "type": "logs",
   "description": "Log of every time \"add to cart\" was clicked and custom event evoked. This can be changed for any custom event configured ex: checkouts completed/initiated. ",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{app=\"$AppName\"} | logfmt | event_name = `CartAdd`"
    }
   ]
  },
  {
   "title": "Sum of all Events in time frame",
   "type": "table",
   "description": "To Do: \nremove non custom events?\n\nrename columns\nremove time\ncheck accuracy\nTurn into filter",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by(event_name) (count_over_time({app=\"test-app2\", kind=\"event\"} | logfmt [$__range]))"
    }
   ]
  }
 ]
}